vendure-ecommerce/ngx-translate-extract

src/parsers/pipe.parser.ts, tests/parsers/pipe.parser.spec.ts
Ported from biesbjerg/ngx-translate-extract#242
Fixes a regression that happened between v3.0.5 and v4.0.0 and is still present, where the pipe parser no longer detects usages like this:
```html
<ng-container *ngTemplateOutlet="section; context: {
title: 'example.translation.key' | translate
}"></ng-container>
```
Turns out it's because inputs to structural directives were not being searched at all. 
This adds handling of `templateAttrs` on `Template` nodes that works identically to inputs.
=> fix(pipe-parser) search for pipe in structural directives

src/parsers/pipe.parser.ts, tests/parsers/pipe.parser.spec.ts
Ported from https://github.com/biesbjerg/ngx-translate-extract/pull/243
This changes `PipeParser` to consider arguments to translate pipe and other pipes in the search for translation keys.
Examples where key did not get extracted previously:
```
{{ 'value' | testPipe: ('test1' | translate) }} // finds nothing, misses 'test1' 
{{ 'Hello' | translate: {world: ('World' | translate)} }} // finds 'Hello', misses 'World'
{{ 'previewHeader' | translate:{filename: filename || ('video' | translate)} }} // finds 'previewHeader', misses 'video'
```
Note the nested usage of translate pipe in the last example.
`expressionIsOrHasBindingPipe` has been simplified and inlined into `getTranslatablesFromAst`, the case of `'key' | foo | ... | bar | translate` is already correctly handled by another …
=> Find uses of translate pipe in pipe arguments

package-lock.json, package.json
Support typescript 5. As far as I see this is the only library that needs to be updated.
@michaelbromley Can you have a look at this? It would be great to have a new version of ngx-translate-extract that is fully compatible with typescript 5.
=> Bump @phenomnomnominal/tsquery to 5.0.1

README.md, src/cli/cli.ts, src/index.ts, src/post-processors/strip-prefix.post-processor.ts, src/utils/translation.collection.ts, tests/post-processors/strip-prefix.post-processor.spec.ts
=> feat: Add post-processor to strip prefix from keys (#16)

.github/workflows/node.js.yml, README.md, package-lock.json, package.json, src/parsers/directive.parser.ts, src/parsers/pipe.parser.ts, tests/parsers/directive.parser.spec.ts, tests/parsers/pipe.parser.spec.ts, tsconfig.json
BREAKING CHANGE
- minimum angular version required bumped to 17
- minimum node version required bumped to v18.13.0 to be aligned with the Angular 17 requirements
- minimum TypeScript version required bumped to v5.2 to be aligned with the Angular 17 requirements
=> feat: Add support for Built-in control flow syntax (#26)

src/cli/tasks/extract.task.ts
After I updated to the latest version the extract task started throwing error:
SyntaxError: the requested module 'glob' does not provide an export named 'default' 
This is due the update of the glob package. It strange that tests and build didn't catch this.
=> fix: Fix import from glob package

src/cli/tasks/extract.task.ts
Maybe I was a little bit too ambitious with the update of the dependencies. I realized earlier that the extract is not picking up keys on my windows machine. The newer versions of `glob` require that the patterns should always use forward slash.
https://github.com/isaacs/node-glob#readme
=> fix: Fix extract not working on windows

src/cli/cli.ts, tsconfig.json
This enables the option to use top level await and is also aligned with the latest angular tsconfig target
=> chore: update tsconfig target and module to es2022

src/parsers/pipe.parser.ts, tests/parsers/pipe.parser.spec.ts
Thank you so much for maintaining this project!
With https://github.com/vendure-ecommerce/ngx-translate-extract/pull/27 we get the exception `RangeError: Maximum call stack size exceeded` on some templates. The `findPipesInNode => extractPipesFromChildNodes => findPipesInNode` recursion on a class fails on depth 18, e.g. this template:
```html
<i><i><i><i><i><i><i><i><i><i><i><i><i><i><i><i><i><i>
{{ 'deep' | translate }}
</i></i></i></i></i></i></i></i></i></i></i></i></i></i></i></i></i></i>
```
Which apparently can happen if you dabble with some nested diffs, forms, bootstrap boilerplate, angular blocks and some ternary to finish it off.
This PR cleans up the recursion via two traversal methods that don't hold much context, allowing to traverse through nested templates (from before …
=> fix(pipe.parser): `RangeError: Maximum call stack size exceeded` on nested templates

src/post-processors/sort-by-key.post-processor.ts, tests/post-processors/sort-by-key.post-processor.spec.ts
Addresses the issue when the `--sort` flag is used, where keys with lowercase characters were incorrectly positioned at the bottom of the file after keys with uppercase characters, breaking the alphabetical order.
Closes #15
=> fix: Fix alphabetical order of extracted keys

README.md, src/cache/cache-interface.ts, src/cache/file-cache.ts, src/cache/null-cache.ts, src/cli/cli.ts, src/cli/tasks/extract.task.ts
used like: 
```sh
ngx-translate-extract --cache-file node_modules/.i18n-cache/my-cache-file --input ./src --output ./src/i18n/{da,en}.json
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
In our project with 1100 scanned files, cached runs go down from 2 seconds to 0.3 seconds. And the terminal is less spamy as it only reports changed files.
The cache is implemented as careful as possible:
* opt-in, so disabled by default (you need to provide `--cache-file` option)
* the only thing that is cached is: "filename + contents" => "parser result"
* removes entries from cache that were unused, to not let stale data linger
* invalidate cache if package.json changes (aka new ngx-translate-extract release)
* the globbing/search for files isn't cached, the extractor still looks at the entire …
=> feat: add an optional cache that speeds up consecutive runs

src/utils/ast-helpers.ts, tests/parsers/service.parser.spec.ts
=> fix: Fix TranslateService not resolved when injected with readonly keyword

src/parsers/pipe.parser.ts, tests/parsers/pipe.parser.spec.ts
seems like KeyedRead was always there, but not detected.
Finds keys in static object and array access, e.g.:
```
{
foo: 'a' | translate,
bar: 'b' | translate,
}[ key ];
```
```
[
'a' | translate,
'b' | translate,
}[ index ];
```
=> feat: support finding translations pipe in KeyedRead nodes

src/parsers/marker.parser.ts, tests/parsers/marker.parser.spec.ts
The issue is that the `tsquery.ast` defaults to parsing the source as TSX, which causes problems when bracket syntax casting (`<Type>`) is used. This is because the parser confuses the casting syntax with JSX. To resolve this, we need to explicitly set the ScriptKind parameter to TS.
In the `ast` function description is also suggested to use `ScriptKind.TS` if the code uses the `<Type>` syntax for casting.
> "If you are using the `<Type>` syntax for casting, you should use `ScriptKind.TS`."
https://github.com/phenomnomnominal/tsquery/blob/master/src/ast.ts#L12
This change ensures that the parser passes the correct `ScriptKind` to the `ast` function based on the source file extension, so that for .ts files it avoids the confusion with JSX and preventing parsing errors.
Fixes #43
=> fix: Fix marker function parsing when used after bracket syntax casting expression

README.md, src/cli/cli.ts, src/index.ts, src/post-processors/key-as-default-value.post-processor.ts, src/post-processors/key-as-initial-default-value.post-processor.ts, tests/post-processors/key-as-initial-default-value.post-processor.spec.ts
Added a copy of the `--key-as-default-value` flag to keep empty translations empty when the `--key-as-initial-default-value` flag is in use. This prevents intentionally emptied translations to not be filled again with the key when it already exists
See https://github.com/vendure-ecommerce/ngx-translate-extract/issues/48
=> feat!: Add check if key is pre-existing

src/parsers/service.parser.ts, src/utils/ast-helpers.ts, tests/parsers/service.parser.spec.ts
I tested it in a couple of small / medium sized projects and there was not any issue. However @michaelbromley if you merge this PR it would be better, if possible, to do a pre-release (beta/ next) before proceeding to a stable release to allow for more testing and make sure that these changes won't cause disruption.
Closes #44
=> feat: Add support for extraction of translation keys from function expressions

src/parsers/function.parser.ts, src/parsers/marker.parser.ts, src/parsers/service.parser.ts, src/utils/ast-helpers.ts, tests/parsers/function.parser.spec.ts, tests/parsers/service.parser.spec.ts, tests/utils/ast-helpers.spec.ts
This is a followup fix from #43 which was only addressing the issue for the `marker` parser. This change also fixes the service and function parser.
Fixes #50
=> fix: Fix service and function parsing when used after bracket syntax casting expression

src/parsers/marker.parser.ts, src/parsers/service.parser.ts, src/utils/ast-helpers.ts, tests/parsers/service.parser.spec.ts, tests/utils/ast-helpers.spec.ts
=> fix: Fix service parser to recognize the `TranslateService` property from an aliased superclass

src/utils/ast-helpers.ts, tests/parsers/service.parser.spec.ts
=> fix: Fix parser not locating `TranslateService` in private fields using the `#` syntax

README.md
Revise the marker function section to reference the implementation from `ngx-translate`.
Closes #4
=> docs: Update marker function documentation

README.md, package-lock.json, package.json, src/parsers/directive.parser.ts, src/parsers/pipe.parser.ts
BREAKING CHANGE
- minimum angular version required bumped to 20
- minimum node version required bumped to v20.19.0 to be aligned with the Angular 20 requirements
- minimum TypeScript version required bumped to v5.8 to be aligned with the Angular 20 requirements
Closes: #76
=> feat: Add support for angular 20

src/parsers/pipe.parser.ts, src/utils/ast-helpers.ts, tests/parsers/pipe.parser.spec.ts, tests/parsers/service.parser.spec.ts
Align extractor behavior with `ngx-translate`, which does not treat empty strings as valid translation keys.
Closes #105
=> fix: exclude empty strings from extracted keys
